apiVersion: 1

contactPoints:
  - orgId: 1
    name: gcp-alert-router
    receivers:
      - uid: gcp-alert-router
        type: webhook
        disableResolveMessage: false
        settings:
          url: $__env{MLP_ALERT_ROUTER_URL}
          httpMethod: POST
          authorization_scheme: Bearer
          authorization_credentials: $__env{MLP_ALERT_ROUTER_TOKEN}
